baseURL = 'https://chinglinghui0328.github.io'
languageCode = 'zh-tw'
title = 'Footprints'
theme = 'PaperMod'

buildDrafts = false 

[[menu.main]]

identifier = "tags"

name = "tags"

url = "/tags/"

weight = 10

[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30

[params.profileMode]
enabled = true
title = "Hui-chingling"
subtitle = "a foodie"
imageUrl = "img/name.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "Enter the content"